"""Transparent tactical hypotheses and matchup analysis."""

from app.tactics.analyst_journal import (
    create_postgame_review,
    create_prediction_log,
    load_postgame_reviews,
    load_prediction_logs,
    summarize_analyst_profile,
)
from app.tactics.data_coverage import load_context_feature_gate, team_data_coverage
from app.tactics.manager_skills import (
    evaluate_decision_rules,
    generate_manager_plan,
    list_manager_skills,
    list_manager_registry,
    load_manager_skill,
    load_team_manager_record,
    load_team_manager_skill,
)
from app.tactics.matchup_engine import (
    build_matchup_edges,
    score_midfield_control,
    score_set_piece_edge,
    score_striker_vs_centerbacks,
    score_transition_risk,
    score_winger_vs_fullback,
)
from app.tactics.player_profiles import (
    get_team_role_depth,
    load_player_availability,
    load_player_profiles,
    load_projected_lineup,
)
from app.tactics.tactical_brief import (
    build_matchup_report,
    build_tactical_brief,
    get_team_manager_overview,
    list_manager_catalog,
    manager_curation_summary,
)
from app.tactics.schemas import (
    AnalystProfile,
    AvailabilityRisk,
    DecisionRule,
    EvidenceReference,
    ManagerPlan,
    ManagerSkill,
    MatchupEdge,
    MatchContext,
    PlayerAvailability,
    PlayerProfile,
    PostgameReview,
    PostgameReviewCreate,
    PredictionLog,
    PredictionLogCreate,
    ProjectedLineupPlayer,
    SubstitutionPattern,
    TacticalBrief,
    TacticalBriefRequest,
    TacticalIdentity,
    TacticalDataCoverage,
    TacticalForecastSnapshot,
    TacticalMatchupRequest,
)

__all__ = [
    "AnalystProfile",
    "AvailabilityRisk",
    "DecisionRule",
    "EvidenceReference",
    "ManagerPlan",
    "ManagerSkill",
    "MatchupEdge",
    "MatchContext",
    "PlayerAvailability",
    "PlayerProfile",
    "PostgameReview",
    "PostgameReviewCreate",
    "PredictionLog",
    "PredictionLogCreate",
    "ProjectedLineupPlayer",
    "SubstitutionPattern",
    "TacticalBrief",
    "TacticalBriefRequest",
    "TacticalForecastSnapshot",
    "TacticalDataCoverage",
    "TacticalIdentity",
    "TacticalMatchupRequest",
    "build_matchup_report",
    "build_tactical_brief",
    "build_matchup_edges",
    "create_postgame_review",
    "create_prediction_log",
    "evaluate_decision_rules",
    "generate_manager_plan",
    "get_team_manager_overview",
    "get_team_role_depth",
    "list_manager_skills",
    "list_manager_registry",
    "list_manager_catalog",
    "manager_curation_summary",
    "load_manager_skill",
    "load_context_feature_gate",
    "load_postgame_reviews",
    "load_prediction_logs",
    "load_player_availability",
    "load_player_profiles",
    "load_projected_lineup",
    "load_team_manager_skill",
    "load_team_manager_record",
    "score_midfield_control",
    "score_set_piece_edge",
    "score_striker_vs_centerbacks",
    "score_transition_risk",
    "score_winger_vs_fullback",
    "summarize_analyst_profile",
    "team_data_coverage",
]
